# Generated by Django 4.1.3 on 2022-11-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='donutions_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='donutions_total',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
