# Generated by Django 4.1.3 on 2022-11-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetusers', '0002_user_donutions_count_user_donutions_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='donutions_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
