# Generated by Django 4.1.3 on 2022-11-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetusers', '0003_alter_user_donutions_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='donutions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='donutions_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
