# Generated by Django 4.1.3 on 2022-11-06 07:39

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweetusers', '0007_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='donation_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='donutions_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='donutions_total',
        ),
        migrations.RemoveField(
            model_name='user',
            name='widget_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='User1667720361', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(storage='templates/avatars/', upload_to='')),
                ('donation_link', models.CharField(blank=True, max_length=255, null=True)),
                ('widget_token', models.CharField(blank=True, max_length=255, null=True)),
                ('donutions_count', models.IntegerField(default=0)),
                ('donutions_total', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
